heart disease/CODE/health_desease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from health.views import *
# from .api import router
from .apirep import routerep

urlpatterns = [
    # path('api/sensoviz/', include(router.urls)),
    path('api/v1/', include(routerep.urls)),
    path('admin/', admin.site.urls),
    path('', Home, name="home"),
    path('patient_home', User_Home,name="patient_home"),
    path('doctor_home', Doctor_Home,name="doctor_home"),
    path('admin_home', Admin_Home,name="admin_home"),
    path('about', About,name="about"),
    path('contact', Contact,name="contact"),
    path('gallery', Gallery,name="gallery"),
    path('login', Login_User,name="login"),
    path('login_admin', Login_admin,name="login_admin"),
    path('signup', Signup_User,name="signup"),
    path('logout', Logout,name="logout"),
    path('change_password', Change_Password,name="change_password"),
    # path('prdict_heart_disease', prdict_heart_disease,name="prdict_heart_disease"),
    path('add_heartdetail', add_heartdetail,name="add_heartdetail"),
    path('view_search_pat', view_search_pat,name="view_search_pat"),

    path('view_doctor', View_Doctor,name="view_doctor"),
    path('add_doctor', add_doctor,name="add_doctor"),
    path('change_doctor/<int:pid>/', add_doctor,name="change_doctor"),
    path('view_patient', View_Patient,name="view_patient"),
    path('view_feedback', View_Feedback,name="view_feedback"),
    path('edit_profile', Edit_My_deatail,name="edit_profile"),
    path('profile_doctor', View_My_Detail,name="profile_doctor"),
    path('sent_feedback', sent_feedback,name="sent_feedback"),

    path('delete_searched/<int:pid>', delete_searched, name="delete_searched"),
    path('delete_doctor<int:pid>', delete_doctor, name="delete_doctor"),
    path('assign_status<int:pid>', assign_status, name="assign_status"),
    path('delete_patient<int:pid>', delete_patient, name="delete_patient"),
    path('delete_feedback<int:pid>', delete_feedback, name="delete_feedback"),
    path('predict_desease/<str:pred>/<str:accuracy>/', predict_desease, name="predict_desease"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heart disease/CODE/health/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from .choices import DOCTOR_STATUS

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    status = models.IntegerField(DOCTOR_STATUS, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    doj = models.DateField(null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Admin_Helath_CSV(models.Model):
    name = models.CharField(max_length=100, null=True)
    csv_file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

class Search_Data(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    prediction_accuracy = models.CharField(max_length=100,null=True,blank=True)
    result = models.CharField(max_length=100,null=True,blank=True)
    values_list = models.CharField(max_length=100,null=True,blank=True)
    created = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.patient.user.username

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    messages = models.TextField(null=True)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.user.username

heart disease/CODE/health/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ('status', 'user', 'dob', 'doj')

heart disease/CODE/health/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
import datetime

from sklearn.ensemble import GradientBoostingClassifier

from .forms import DoctorForm
from .models import *
from django.contrib.auth import authenticate, login, logout
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from django.http import HttpResponse
# Create your views here.

def Home(request):
    return render(request,'carousel.html')

def Admin_Home(request):
    dis = Search_Data.objects.all()
    pat = Patient.objects.all()
    doc = Doctor.objects.all()
    feed = Feedback.objects.all()

    d = {'dis':dis.count(),'pat':pat.count(),'doc':doc.count(),'feed':feed.count()}
    return render(request,'admin_home.html',d)

@login_required(login_url="login")
def assign_status(request,pid):
    doctor = Doctor.objects.get(id=pid)
    if doctor.status == 1:
        doctor.status = 2
        messages.success(request, 'Selected doctor are successfully withdraw his approval.')
    else:
        doctor.status = 1
        messages.success(request, 'Selected doctor are successfully approved.')
    doctor.save()
    return redirect('view_doctor')

@login_required(login_url="login")
def User_Home(request):
    return render(request,'patient_home.html')

@login_required(login_url="login")
def Doctor_Home(request):
    return render(request,'doctor_home.html')

def About(request):
    return render(request,'about.html')

def Contact(request):
    return render(request,'contact.html')


def Gallery(request):
    return render(request,'gallery.html')


def Login_User(request):
    error = ""
    if request.method == "POST":
        u = request.POST['uname']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        sign = ""
        if user:
            try:
                sign = Patient.objects.get(user=user)
            except:
                pass
            if sign:
                login(request, user)
                error = "pat1"
            else:
                pure=False
                try:
                    pure = Doctor.objects.get(status=1,user=user)
                except:
                    pass
                if pure:
                    login(request, user)
                    error = "pat2"
                else:
                    login(request, user)
                    error="notmember"
        else:
            error="not"
    d = {'error': error}
    return render(request, 'login.html', d)

def Login_admin(request):
    error = ""
    if request.method == "POST":
        u = request.POST['uname']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        if user.is_staff:
            login(request, user)
            error="pat"
        else:
            error="not"
    d = {'error': error}
    return render(request, 'admin_login.html', d)

def Signup_User(request):
    error = ""
    if request.method == 'POST':
        f = request.POST['fname']
        l = request.POST['lname']
        u = request.POST['uname']
        e = request.POST['email']
        p = request.POST['pwd']
        d = request.POST['dob']
        con = request.POST['contact']
        add = request.POST['add']
        type = request.POST['type']
        im = request.FILES['image']
        dat = datetime.date.today()
        user = User.objects.create_user(email=e, username=u, password=p, first_name=f,last_name=l)
        if type == "Patient":
            Patient.objects.create(user=user,contact=con,address=add,image=im,dob=d)
        else:
            Doctor.objects.create(dob=d,image=im,user=user,contact=con,address=add,status=2)
        error = "create"
    d = {'error':error}
    return render(request,'register.html',d)

def Logout(request):
    logout(request)
    return redirect('home')

@login_required(login_url="login")
def Change_Password(request):
    sign = 0
    user = User.objects.get(username=request.user.username)
    error = ""
    if not request.user.is_staff:
        try:
            sign = Patient.objects.get(user=user)
            if sign:
                error = "pat"
        except:
            sign = Doctor.objects.get(user=user)
    terror = ""
    if request.method=="POST":
        n = request.POST['pwd1']
        c = request.POST['pwd2']
        o = request.POST['pwd3']
        if c == n:
            u = User.objects.get(username__exact=request.user.username)
            u.set_password(n)
            u.save()
            terror = "yes"
        else:
            terror = "not"
    d = {'error':error,'terror':terror,'data':sign}
    return render(request,'change_password.html',d)


def preprocess_inputs(df, scaler):
    df = df.copy()
    # Split df into X and y
    y = df['target'].copy()
    X = df.drop('target', axis=1).copy()
    X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
    return X, y


def prdict_heart_disease(list_data):
    csv_file = Admin_Helath_CSV.objects.get(id=1)
    df = pd.read_csv(csv_file.csv_file)

    X = df[['age','sex','cp',  'trestbps',  'chol',  'fbs',  'restecg',  'thalach',  'exang',  'oldpeak',  'slope',  'ca',  'thal']]
    y = df['target']
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, stratify=y, random_state=2)
   
    nn_model = KNeighborsClassifier()
    nn_model.fit(X_train, y_train)
    pred = nn_model.predict([list_data])
    print("Neural Network Accuracy: {:.2f}%".format(nn_model.score(X_test, y_test) * 100))
    print("Prdicted Value is : ", format(pred))
    dataframe = str(df.head())
    return (nn_model.score(X_test, y_test) * 100),(pred)

@login_required(login_url="login")
def add_doctor(request,pid=None):
    doctor = None
    if pid:
        doctor = Doctor.objects.get(id=pid)
    if request.method == "POST":
        form = DoctorForm(request.POST, request.FILES, instance = doctor)
        if form.is_valid():
            new_doc = form.save()
            new_doc.status = 1
            if not pid:
                user = User.objects.create_user(password=request.POST['password'], username=request.POST['username'], first_name=request.POST['first_name'], last_name=request.POST['last_name'])
                new_doc.user = user
            new_doc.save()
            return redirect('view_doctor')
    d = {"doctor": doctor}
    return render(request, 'add_doctor.html', d)

@login_required(login_url="login")
def add_heartdetail(request):
    if request.method == "POST":
        # list_data = [57, 0, 1, 130, 236, 0, 0, 174, 0, 0.0, 1, 1, 2]
        list_data = []
        value_dict = eval(str(request.POST)[12:-1])
        count = 0
        for key,value in value_dict.items():
            if count == 0:
                count =1
                continue
            if key == "sex" and value[0] == "Male" or value[0] == 'male' or value[0]=='m' or value[0] == 'M':
                list_data.append(0)
                continue
            elif key == "sex":
                list_data.append(1)
                continue
            list_data.append(value[0])

        # list_data = [57, 0, 1, 130, 236, 0, 0, 174, 0, 0.0, 1, 1, 2]
        accuracy,pred = prdict_heart_disease(list_data)
        patient = Patient.objects.get(user=request.user)
        Search_Data.objects.create(patient=patient, prediction_accuracy=accuracy, result=pred[0], values_list=list_data)
        rem = int(pred[0])
        print("Result = ",rem)
        if pred[0] == 0:
            pred = "<span style='color:green'>You are Heart failure </span>"
        elif pred[0] == 1:
            pred = "<span style='color:red'>You are Myocardial infraction , Need to Checkup.</span>"
        elif pred[0] == 2:
            pred = "<span style='color:red'>You are MDilated cardiomyopathy , Need to Checkup.</span>"
        elif pred[0] == 3:
            pred = "<span style='color:red'>You are Coronary vasaspasm , Need to Checkup.</span>"
        elif pred[0] == 4:
            pred = "<span style='color:red'>You are Atrial fibrillation, Need to Checkup.</span>"
        else:
            pred = "<span style='color:red'>You are Arrhythmia- abnormal heart rythmn, Need to Checkup.</span>"
        return redirect('predict_desease', str(rem), str(accuracy))
    return render(request, 'add_heartdetail.html')

@login_required(login_url="login")
def predict_desease(request, pred, accuracy):
    doctor = Doctor.objects.filter(address__icontains=Patient.objects.get(user=request.user).address)
    d = {'pred': pred, 'accuracy':accuracy, 'doctor':doctor}
    return render(request, 'predict_disease.html', d)

@login_required(login_url="login")
def view_search_pat(request):
    doc = None
    try:
        doc = Doctor.objects.get(user=request.user)
        data = Search_Data.objects.filter(patient__address__icontains=doc.address).order_by('-id')
    except:
        try:
            doc = Patient.objects.get(user=request.user)
            data = Search_Data.objects.filter(patient=doc).order_by('-id')
        except:
            data = Search_Data.objects.all().order_by('-id')
    return render(request,'view_search_pat.html',{'data':data})

@login_required(login_url="login")
def delete_doctor(request,pid):
    doc = Doctor.objects.get(id=pid)
    doc.delete()
    return redirect('view_doctor')

@login_required(login_url="login")
def delete_feedback(request,pid):
    doc = Feedback.objects.get(id=pid)
    doc.delete()
    return redirect('view_feedback')

@login_required(login_url="login")
def delete_patient(request,pid):
    doc = Patient.objects.get(id=pid)
    doc.delete()
    return redirect('view_patient')

heart disease/CODE/health/templates/admin_login.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
{% if error == "pat" %}
<script>
    alert('logged in successfully');
    window.location=('{% url 'admin_home' %}');
</script>
{% endif %}

{% if error == "notmember" %}
<script>
    alert('Your information is pending.plz Update Your Profile 1st.then continue this service');
    window.location=('{% url 'service_home' %}');
</script>
{% endif %}
{% if error == "pat2" %}
<script>
    alert('logged in successfully');
    window.location=('{% url 'admin_home' %}');
</script>
{% endif %}
{% if error == "not" %}
<script>
    alert('Username & Password are not Matching');
</script>
{% endif %}

	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<br><br>
				<center>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Login</h3>
				</center>
			</div><hr/>
			<div class="login px-sm-4 mx-auto mw-100 login-wrapper">
				<form class="login-wrapper" action="" method="post">
                    {% csrf_token %}
					<div class="form-group">
						<label>Username</label>
						<input type="text" class="form-control" name="uname" placeholder="Enter Username" required="">
						<small id="emailHelp" class="form-text text-muted">Your privacy is our priority.</small>
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" class="form-control" name="pwd" placeholder="Enter Your Password" required="">
					</div>
					<center>
					<button type="submit" class="btn submit mt-4" style="background: #6a6b6c;">Login</button>
					</center>
				</form>
			</div>
		</div>
	</section>

{% endblock %}

heart disease/CODE/health/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
	<title>Heart Disease Prediction System</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link href="{% static 'css/css_slider.css' %}" type="text/css" rel="stylesheet" media="all">
	<!-- banner slider -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Mukta:200,300,400,500,600,700,800&amp;subset=devanagari,latin-ext" rel="stylesheet">
<style>	<!-- //Web-Fonts -->
.li2{
	border:1px solid red;
	padding:8px;
	}
</style>

<link rel='stylesheet' type='text/css' href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<link rel='stylesheet' type='text/css' href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>

<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>
</head>

<body>
	<!-- main -->
	<div id="home" style="margin-bottom:2%">
		<!-- top header -->
		<header>
			<div class="top-bar py-3">
				<div class="container">
					<div class="row">
						
						<div class="col-xl-7 col-lg-6 col-md-4 top-social-agile text-md-right text-center mt-md-0 mt-2">
							<div class="row">
								<div class="offset-xl-6 offset-lg-4">
								</div>
								<div class="col-xl-3 col-lg-4 col-6 top-w3layouts p-md-0 text-right">
									<!-- login -->
									<a href="login.html" class="login-button-2 text-uppercase text-bl">
										</a>
									<!-- //login -->
								</div>
								<div class="col-xl-3 col-lg-4 col-6 header-w3layouts text-md-right text-left">
									<!-- register -->
									<a href="register.html" class="login-button-2 text-uppercase text-bl">
										</a>
									<!-- //register -->
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<!-- //top header -->

		<!-- second header -->
		<div class="main-top" style="background:rgb(44, 164, 182)">
			<div class="container-fluid">
				<div class="header d-md-flex justify-content-between align-items-center py-3">
					<!-- logo -->
					<div id="logo" style="margin-left:13%">
						<h1>
							<a href="index.html">
								<span class="fa fa-user-md mr-2"></span>
								<span class="logo-sp">Heart Disease</span> Prediction
							</a>
						</h1>
					</div>
					<!-- //logo -->
					<!-- nav -->
					{% if request.user.is_staff %}
					<div class="nav_w3ls" style="margin-right:4%">
						<nav>
							<label for="drop1" class="toggle">Menu</label>
							<input type="checkbox" id="drop1" />
							<ul class="menu" style="padding:15px;width:100%">

								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="{% url 'admin_home' %}" >Home</a></li>

								<li>
									<label for="drop-2" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"> Doctor <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:2%;width:40%;margin-right:0%">
										<li style="width:100%;"><a href="/add_doctor" class="drop-text">Add Doctor</a></li>
										<li style="width:100%;"><a href="/view_doctor" class="drop-text">View Doctor</a></li>
									</ul>
								</li>



								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/view_patient">Patient</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="/view_search_pat">Searched Data</a></li>
								<li><a href="/view_feedback">Feedback</a></li>

							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop2" class="toggle">Menu</label>
							<input type="checkbox" id="drop2" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:red;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-user"></i> {{request.user.username}} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:10%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'change_password' %}" class="drop-text">Password</a></li>
										<li style="width:100%;"><a href="{% url 'logout' %}" class="drop-text">Logout</a></li>
									</ul>
								</li>



							</ul>
						</nav>
					</div>

					{% elif request.user.patient_set.all.0 %}
					<div class="nav_w3ls" style="margin-left:5%;font-weight:bold">
						<nav>
							<label for="drop3" class="toggle">Menu</label>
							<input type="checkbox" id="drop3" />
							<ul class="menu" style="padding:15px;width:100%">
								<li><a href="{% url 'patient_home' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/add_heartdetail">Predict</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/profile_doctor">My Detail</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2"><a href="/sent_feedback">Feedback</a></li>
								<li><a href="/view_search_pat">History</a></li>
							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop4" class="toggle">Menu</label>
							<input type="checkbox" id="drop4" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:#6a6767;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop-3" class="toggle toogle-3"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-sign-in"></i> Hello,{{request.user.username}} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:8%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'change_password' %}" class="drop-text"> Password</a></li>
										<li style="width:100%;"><a href="{% url 'logout' %}" class="drop-text"> Logout</a></li>
									</ul>
								</li>
							</ul>
						</nav>
					</div>
					{% elif request.user.doctor_set.all.0 %}
					<div class="nav_w3ls" style="margin-right:4%">
						<nav>
							<label for="drop5" class="toggle">Menu</label>
							<input type="checkbox" id="drop5" />
							<ul class="menu" style="padding:15px;width:100%">
								<li><a href="{% url 'doctor_home' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="/profile_doctor">My Detail</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="view_search_pat">Searched Data</a></li>

							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop6" class="toggle">Menu</label>
							<input type="checkbox" id="drop6" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:#6a6767;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop6" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-user"></i> {{request.user.username}} <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:10%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'change_password' %}" class="drop-text">Password</a></li>
										<li style="width:100%;"><a href="{% url 'logout' %}" class="drop-text">Logout</a></li>
									</ul>
								</li>



							</ul>
						</nav>
					</div>
					{% else %}
					<div class="nav_w3ls" style="margin-right:4%">
						<nav>
							<label for="drop7" class="toggle">Menu</label>
							<input type="checkbox" id="drop7" />
							<ul class="menu" style="padding:15px;width:100%">
								<li><a href="{% url 'home' %}" class="active">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<a href="{% url 'about' %}">About Us</a></li>
								<li><a href="{% url 'contact' %}"></a></li>
							</ul>
						</nav>
					</div>
					<div class="nav_w3ls" style="margin-right:3%">

						<nav>
							<label for="drop" class="toggle">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2" style="background:#6a6767;padding:8px">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle toogle-2"> <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#"><i class="fa fa-sign-in"></i> Login <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<ul style="margin-top:10%;width:80%;margin-right:5%">
										<li style="width:100%;"><a href="{% url 'login_admin' %}" class="drop-text">Admin</a></li>
										<li style="width:100%;"><a href="{% url 'login' %}" class="drop-text">User</a></li>
									</ul>
								</li>



							</ul>
						</nav>
					</div>
					{% endif %}


					<!-- //nav -->
				</div>
			</div>
		</div>
		<!-- //second header -->

		<!-- banner -->
		{% block body %}
		{% endblock %}
		<!-- //banner -->
	</div>
	<!-- //main -->


	<!-- footer bottom -->
	<!-- copyright -->
	<div class="copy-w3pvt" style="background:rgb(44, 164, 182);color:white">
		<div class="container py-3">
			<div class="row">
				<div class="col-lg-7 w3ls_footer_grid1_left text-lg-left text-center">
					<p style="color:white">&copy; </a>
					</p>
				</div>
				<div class="col-lg-5 w3ls_footer_grid_left1_pos text-lg-right text-center mt-lg-0 mt-2">
					<ul style="color:white">
						<li>
							<a href="#" style="color:white" class="facebook">
								<span class="fa fa-facebook-f mr-2"></span>Facebook</a>
						</li>
						<li class="mx-3">
							<a href="#" style="color:white" class="twitter">
								<span class="fa fa-twitter mr-2"></span>Twitter</a>
						</li>
						<li>
							<a href="#" style="color:white" class="google">
								<span class="fa fa-google-plus mr-2"></span>Google Plus</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<a href="#home" style="color:white" class="move-top text-center"></a>

</body>

</html>